#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/256x256/apps/
cp \
  /usr/share/icons/hicolor/256x256/apps/krita.png \
  $HOME/.local/share/icons/hicolor/256x256/apps/
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/org.kde.krita.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/org.kde.krita.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/org.kde.krita.desktop
