#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/256x256/apps/krita.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/org.kde.krita.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/org.kde.krita.desktop
